---
trigger: none
pr: none
pool: Default

parameters:
- name: resourceGroupName
  displayName: Resource Group Name
  type: string

resources:
  repositories:
  - repository: OutSystems/opscloud-opscoaching
    type: github
    endpoint: 'Coaching Infrastructure Provisioning'
    name: 'OutSystems/opscloud-opscoaching'

jobs:
- job: os_infra_start
  displayName: 'OutSystems Infra Start'
  workspace:
    clean: all
  steps:

  - checkout: OutSystems/opscloud-opscoaching
    clean: true
    displayName: 'Start Infrastucture Script'
  



  - task: AzureCLI@2
    inputs:
      azureSubscription: 'ospsopscloud'
      ScriptType: 'ps'
      scriptLocation: 'InlineScript'
      inlineScript: |
        $vmNamesToBeStarted = Get-AzureRmVM -ResourceGroupName "${{ parameters.resourceGroupName }}"
        foreach($vmName in $vmNamesToBeStarted.name)
        {
            $resource = Get-AzureRmResourceGroup -name "${{ parameters.resourceGroupName }}"
            if($vmName -ne $null)
            {  
                Write-Output "Starting virtual machine..." + $vmName
                Start-AzureRmVM -Name $vmName -ResourceGroupName $resource.ResourceGroupName
            }   
            else
            {
                Write-output "Virtual machine not found:" + $vmName
            }
        }
      workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Start Coaching Virtual Machines'
...
