---
trigger: none
pr: none
pool: Default

parameters:
- name: resourceRegion
  displayName: Resource Region
  type: string
  default: westeurope
- name: clientName
  displayName: Client Name
  type: string
- name: coachingPersons
  type: string

resources:
  repositories:
  - repository: joaooamaral/platform_ops_coaching
    type: github
    endpoint: 'joaooamaral'
    name: 'joaooamaral/platform_ops_coaching'

jobs:
- job: os_infra_bootup
  displayName: 'OutSystems Infra bootup'
  workspace:
    clean: all
  steps:

  - checkout: joaooamaral/platform_ops_coaching
    clean: true
    displayName: 'Checkout Infrastucture Scripts'
  
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'ospsopscloud'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: 'az --version'
      useGlobalConfig: true
      workingDirectory: '$(System.DefaultWorkingDirectory)\terraform\'
    displayName: 'Init Terraform Script'
...
