---
trigger: none
pr: none
pool: Default

parameters:
- name: resourceRegion
  displayName: Resource Region
  type: string
  default: westeurope
- name: clientName
  displayName: Client Name
  type: string
- name: coachingPersons
  type: string
  default: false

resources:
  repositories:
  - repository: joaooamaral/platform_ops_coaching
    type: github
    endpoint: 'joaooamaral'
    name: 'joaooamaral/platform_ops_coaching'

jobs:
- job: os_infra_bootup
  displayName: 'OutSystems Infra bootup'
  workspace:
    clean: all
  steps:

  - checkout: joaooamaral/platform_ops_coaching
    clean: true
    displayName: 'Checkout Infrastucture Scripts'
   
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Infra Bootcamp Automation'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: 'terraform init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\terraform\'
    displayName: 'Init Terraform Script'

  - task: TerraformTaskV1@0
    inputs:
      provider: 'azurerm'
      command: 'apply'
      commandOptions: '-auto-approve -var="client-name=${{ parameters.clientName }}" -var="location=${{ parameters.resourceRegion }}" -var="coaching-persons=${{ parameters.coachingPersons }}"'
      environmentServiceNameAzureRM: 'ospsopscloud'
      workingDirectory: '$(System.DefaultWorkingDirectory)\terraform\'
    timeoutInMinutes: 0
    displayName: 'Run Terraform Script'

...
