---
trigger: none
pr: none
pool: Default

parameters:
- name: resourceGroupName
  displayName: Resource Group Name
  type: string

resources:
  repositories:
  - repository: OutSystems/opscloud-opscoaching
    type: github
    endpoint: 'Coaching Infrastructure Provisioning'
    name: 'OutSystems/opscloud-opscoaching'

jobs:
- job: os_infra_destroy
  displayName: 'OutSystems Infra Destroy'
  workspace:
    clean: all
  steps:

  - checkout: OutSystems/opscloud-opscoaching
    clean: true
    displayName: 'Destroy Infrastucture Script'
  
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'ospsopscloud'
      ScriptType: 'InlineScript'
      Inline: |
        $rgToDelete = (az group show -n "${{ parameters.resourceGroupName }}") | ConvertFrom-Json | Select -expand name
        if ( $rgToDelete )
        {
          Write-Output "Resource Group $rgToDelete exists and will now be deleted"
          az group delete -y -n "${{ parameters.resourceGroupName }}"
        }
        else 
        {
          Write-Output "The Resource Group ${{ parameters.resourceGroupName }} that you entered does not exist... Please reenter the correct name and try again."
          Exit
        }
        Write-Host "Completed deletion of ${{ parameters.resourceGroupName }} Resource Group"
        Write-Host "Starting the deletion of Windows Scheduled Tasks"
        Unregister-ScheduledTask -TaskName '${{ parameters.resourceGroupName }}-Stop' -Confirm:$false
        Unregister-ScheduledTask -TaskName '${{ parameters.resourceGroupName }}-Start' -Confirm:$false
        Write-Host "Completed deletion of Windows Scheduled Tasks"
      azurePowerShellVersion: 'LatestVersion'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Delete infra resources'
...
