---
trigger: none
pr: none
pool: Default

parameters:
- name: resourceRegion
  displayName: Resource Region
  type: string
  default: westeurope
- name: clientName
  displayName: Client Name
  type: string
- name: coachingPersons
  type: string

resources:
  repositories:
  - repository: OutSystems/opscloud-opscoaching
    type: github
    endpoint: 'Coaching Infrastructure Provisioning'
    name: 'OutSystems/opscloud-opscoaching'

jobs:
- job: os_infra_bootup
  displayName: 'OutSystems Infra bootup'
  workspace:
    clean: all
  steps:

  - checkout: OutSystems/opscloud-opscoaching
    clean: true
    displayName: 'Checkout Infrastucture Scripts'
  

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'ospsopscloud'
      ScriptType: 'ps'
      scriptLocation: 'InlineScript'
      inlineScript: 'terraform init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\terraform\'
    displayName: 'Init Terraform Script'


  - task: TerraformCLI@0
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)\terraform\'
      environmentServiceName: 'ospsopscloud'
      commandOptions: '-auto-approve -var="client-name=${{ parameters.clientName }}" -var="location=${{ parameters.resourceRegion }}" -var="coaching-persons=${{ parameters.coachingPersons }}"'
      allowTelemetryCollection: false
    displayName: 'Run Terraform Script'
...
